export const RoutePaths = {
  Home: "/",
  Signup: "/signup",
  Login: "/login",
  Profile: "/user",
  Checkout: "/checkout",
  Cart: "/cart",
  Wishlist: "/wishlist",
  OrderPlaced: "/orderPlaced",
  OrderHistory: "/orderHistory",
  Dashboard: "/dashboard/:search?",
  ResetPassword: "/reset-password",
  ForgotPassword: "/forgot-password",
  Product: "/product/:name",
  Admin: "/admin",
  AddProduct: "/addProduct",
  EditProduct: "/editProduct/:id",
};
